#!/bin/bash

set -e

# Source debconf library
. /usr/share/debconf/confmodule

case "$1" in
    configure)
        # Install udev rule
        if [ -f /usr/share/rpi-keyboard-config/99-rpi-keyboard.rules ]; then
            cp /usr/share/rpi-keyboard-config/99-rpi-keyboard.rules /etc/udev/rules.d/
            echo "Installed udev rule for RPi keyboards"
            
            # Reload udev rules
            if command -v udevadm >/dev/null 2>&1; then
                udevadm control --reload-rules
                udevadm trigger --subsystem-match=hidraw
                echo "Reloaded udev rules"
            fi
        fi
        ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0